logging:
  level:
    root: OFF
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_load_data
    username: postgres
    password: root
    validationQuery: SELECT 1
    testOnBorrow: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
